from typing import Optional, Dict, Any, List, Protocol

class UserRepositoryPort(Protocol):
    def save(self, user_data: Dict[str, Any]) -> Dict[str, Any]: ...
    def find_by_id(self, user_id: int) -> Optional[Dict[str, Any]]: ...
    def find_by_email(self, email: str) -> Optional[Dict[str, Any]]: ...
    def delete(self, user_id: int) -> bool: ...

class TaskRepositoryPort(Protocol):
    def save(self, task_data: Dict[str, Any]) -> Dict[str, Any]: ...
    def find_by_id(self, task_id: int) -> Optional[Dict[str, Any]]: ...
    def find_by_user_id(self, user_id: int, skip: int = 0, limit: int = 100) -> List[Dict[str, Any]]: ...
    def delete(self, task_id: int) -> bool: ...

class NotificationPort(Protocol):
    def notify_user_created(self, username: str, email: str) -> None: ...
    def notify_user_deleted(self, username: str) -> None: ...
    def notify_task_created(self, title: str, status: str) -> None: ...
    def notify_task_updated(self, title: str, status: str) -> None: ...
    def notify_task_deleted(self, title: str) -> None: ...